### ISSUE TITLE
Layout issue on mobile

### ISSUE THREAD

**Issue by CPatchane** [cozy/cozy-ui#451] opened 2018-04-25 13:24 UTC
It seems that the `height: auto` on `html, body` and `o-layout--2panes main` is broking the app content if some elements are using absolute position. An example, the spinner in the cozy-store when apps are being fetching.
Here is the fix I had to do for the Store:
```stylus
// FIXME temporary cozy-ui layout fixes
html, body
    height 100%!important
.o-layout--2panes
    height 100%!important
    position relative
    @media (max-width: (1024/basefont)rem)
        main
            height calc(100% - 3rem - 3rem)
```

**Comment by ptbrowne** [comment] 2018-05-01 00:09
Thanks for reporting the problem :) Can you provide an example of what breaks ?

Also, FYI, there are helpers that help you apply breakpoints in a more readable way : https://github.com/cozy/cozy-ui/blob/6a504f63f316454ea1da94dd5053159d9a0b3241/stylus/settings/breakpoints.styl

**Comment by GoOz** [comment] 2018-05-02 08:01
@ptbrowne I discussed this with @CPatchane already (made him write this issue to help me not forget) but I'm not sure it is related to the layout itself, I must investigate on this first but I think it's more an issue of implementation.

**Comment by GoOz** [comment] 2018-08-07 09:42
This has to be checked first, but maybe not.

**Comment by poupotte** [comment] 2018-12-07 09:39
@CPatchane : Is still relevant ?

**Comment by CPatchane** [comment] 2018-12-07 10:59
I don'k know, @GoOz ? You may want to close this issue if it's good now

**Comment by GoOz** [comment] 2018-12-07 13:13
@CPatchane Well I don't know if it's good now but I can't reproduce.

**Comment by ptbrowne** [comment] 2018-12-07 13:24
Closing since nobody reproduces.

**Closed by ptbrowne** 2018-12-07 13:24 UTC
Labels: bug
