### ISSUE TITLE
Errors in test 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1017] opened 2019-05-29 09:55 UTC
When we run `tests`, we got a lot of error / warning on the console. It makes difficult to really see where the real errors are.  

```
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `StateHolder`.]
        at reportException (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at replayUnitOfWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17107:5)
        at renderRoot (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17979:13) { Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `StateHolder`.
        at invariant (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:55:15)
        at createFiberFromTypeAndProps (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:9958:11)
        at createFiberFromElement (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:9979:15)
        at reconcileSingleElement (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:13654:23)
        at reconcileChildFibers (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:13711:35)
        at reconcileChildren (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:14078:28)
        at finishClassComponent (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:14318:5)
        at updateClassComponent (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:14264:10)
        at beginWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:15082:16)
        at performUnitOfWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17820:12)
        at workLoop (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17860:24)
        at HTMLUnknownElement.callCallback (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:149:14)
        at invokeEventListeners (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:199:16)
        at invokeGuardedCallback (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:256:31)
        at replayUnitOfWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17107:5)
        at renderRoot (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:17979:13)
        at performWorkOnRoot (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18837:7)
        at performWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18749:7)
        at performSyncWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18723:3)
        at requestWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18592:5)
        at scheduleWork (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18401:5)
        at scheduleRootUpdate (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19069:3)
        at updateContainerAtExpirationTime (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19097:10)
        at updateContainer (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19154:10)
        at ReactRoot.Object.<anonymous>.ReactRoot.render (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19416:3)
        at /home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19556:14
        at unbatchedUpdates (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:18952:10)
        at legacyRenderSubtreeIntoContainer (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19552:5)
        at Object.render (/home/travis/build/cozy/cozy-ui/node_modules/react-dom/cjs/react-dom.development.js:19613:12)
        at render (/home/travis/build/cozy/cozy-ui/node_modules/react-styleguidist/lib/rsg-components/Preview/Preview.js:108:15)
        at Timeout.callback [as _onTimeout] (/home/travis/build/cozy/cozy-ui/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5) name: 'Invariant Violation', framesToPop: 1 }
```

```
console.error node_modules/react/cjs/react.development.js:225
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `StateHolder`.
        in StateHolder (created by ReactExample)
        in Wrapper (created by ReactExample)
        in ReactExample
console.error node_modules/react/cjs/react.development.js:225
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `StateHolder`.
        in StateHolder (created by ReactExample)
        in Wrapper (created by ReactExample)
        in ReactExample
```

**Comment by y-lohse** [comment] 2019-05-29 16:02
Duplicate of #772

**Closed by y-lohse** 2019-05-29 16:02 UTC
