### ISSUE TITLE
Modal makes the window scroll to top

### ISSUE THREAD

**Issue by lespacedunmatin** [cozy/cozy-ui#89] opened 2017-03-28 16:30 UTC
When a modal opens-up on a scrolled down window, the window scrolls up to the top.

**Comment by GoOz** [comment] 2017-03-28 16:47
That's odd…  the modal container has a `position: fixed` now. Are you sure you're using the last release of Cozy-UI and that the link/button that opens up the modal doesn't have an anchor as `href `? Both could explain it.

**Comment by lespacedunmatin** [comment] 2017-03-29 08:08
Settings use cozy-ui 3.0.0beta18 (see https://github.com/cozy/cozy-settings/blob/master/package.json#L83).

**Comment by GoOz** [comment] 2017-03-29 08:51
Indeed, I can reproduce. I can't see why but it definitely needs a deeper investigation.

**Comment by enguerran** [comment] 2017-03-29 13:57
I did not test the code on my own, but as far as I know the content may scroll up because of a preact render. If the DOM is refreshed, the view will be repaint.
It won't be related to the modal, but to the DOM update after the modal call.

**Comment by GoOz** [comment] 2017-03-29 14:04
@enguerran I feared that but wasn't sure. That sucks. But i'll take a look later.

**Comment by y-lohse** [comment] 2017-03-31 07:50
I've been thinking about this as we keep having this problem. I wonder if we shound't ditch the `myCondition && <Component />` approach, and do something like `<Component visible={myCondition} />`. Then of course the component has to handle that flag, but at least the repaint won't affect anything else, right?

**Comment by GoOz** [comment] 2017-03-31 07:54
@y-lohse You got me there, you're sure this is the problem or you guess it is?

**Comment by y-lohse** [comment] 2017-03-31 07:56
No, just based on what @enguerran says. We'd have to confirm it, but yeah, it sounds very likely.

**Comment by GoOz** [comment] 2017-03-31 07:57
Ok then, I'll let someone more "javascripty" than me take this one. 😄

**Comment by GoOz** [comment] 2017-12-15 23:58
I can't reproduce it anymore, did we just fixed by accident? Maybe the new modal fixed it.

Any thought on this @y-lohse @ptbrowne ?

**Comment by ptbrowne** [comment] 2017-12-17 11:58
I never saw this bug with the Modal component, I think we can close.

**Comment by ptbrowne** [comment] 2017-12-17 12:00
@y-lohse please reopen if you have seen this issue ;)

**Closed** 2017-12-17 11:59 UTC
Labels: ☠️ bug
