### ISSUE TITLE
2 small bugs on the storybook

### ISSUE THREAD

**Issue by nono** [cozy/cozy-ui#210] opened 2017-11-07 08:13 UTC
- [ ] the paperplane icon is not shown
- [x] the grey and white spinners are blue

**Comment by enguerran** [comment] 2017-11-07 08:26
We don't use storybook, but [styleguidist](https://github.com/styleguidist/react-styleguidist). Comment stay relevant.

**Comment by nono** [comment] 2017-11-07 08:27
It's called the storybook in the README: https://github.com/cozy/cozy-ui#react-components

**Comment by ptbrowne** [comment] 2017-11-07 15:58
Spinner problems are duplicate of https://github.com/cozy/cozy-ui/issues/197

**Closed** 2017-12-11 13:41 UTC
Labels: ☠️ bug

**Comment by ptbrowne** [comment] 2017-12-11 13:46
Thanks @nono for the report. Both bugs are fixed
