### ISSUE TITLE
Selector component ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#269] opened 2017-12-20 12:43 UTC
We have this component in Bank and Santé. Current behavior : 

- Menu should take all screen on mobile
- Menu should be opened from the selector on Desktop
- It should have a small chevron to the right
- There should be an Overlay when opened

So it seems it is quite like a Menu except that it has an overlay and a different behavior on mobile. What do you think @gooz ?

![image](https://user-images.githubusercontent.com/465582/34207533-2daf15cc-e58b-11e7-957b-ee94c5350638.png)

![image](https://user-images.githubusercontent.com/465582/34207548-3b41e494-e58b-11e7-85f9-53c5c1453db9.png)

I am open for a different name.

**Comment by GoOz** [comment] 2017-12-20 15:11
I don't really know this one.
Before anything I'd rather talk about it with @Claiw, but yeah it seems it could belong to UI.
Not sure about the name though.

**Comment by ptbrowne** [comment] 2017-12-20 16:05
>  Before anything I'd rather talk about it with @Claiw, but yeah it seems it could belong to UI.

👌

**Comment by Claiw** [comment] 2017-12-21 14:46
The behavior seems ok for me.
In the mockups, this component is called "Popover"; I have too a mockup named as "selection open" which describes the behavior 
Perhaps Selection-menu or Selection-list ?

**Comment by goldoraf** [comment] 2017-12-21 14:55
Regarding to the naming issue, I think what we have here is a Menu in a Popover, like here: http://www.material-ui.com/#/components/popover

**Comment by y-lohse** [comment] 2018-03-16 08:56
We have similar use-cases on Contacts:

<img width="409" alt="capture d ecran 2018-03-16 09 06 12" src="https://user-images.githubusercontent.com/2261445/37509874-7a258c7c-28f9-11e8-94c6-9713286cfcda.png">

A button with a dropdown indicator, a list of selectable items, a form at the end.

<img width="409" alt="capture d ecran 2018-03-16 09 05 55" src="https://user-images.githubusercontent.com/2261445/37509887-8bcf5520-28f9-11e8-9ffd-4bad5771bfaa.png">

Same thing, but each option has a checkbox net to it and you can pick more than one.

<img width="904" alt="capture d ecran 2018-03-16 09 09 07" src="https://user-images.githubusercontent.com/2261445/37509930-b1ec4772-28f9-11e8-99b4-b995b766a5ed.png">

An interactive option that contains buttons, and you can turn it into an editable field.

________________

I'm currently working on implementing the second one, and I've more or less done it using [`react-select` v2](https://deploy-preview-2289--react-select.netlify.com/home) (currently in alpha).

[This is what the implementation looks like at the moment](https://github.com/y-lohse/cozy-contacts/blob/9730af3394e891badd93df5ebe721ea2a0aed202/src/components/ContactGroups/ContactGroupManager.jsx). 
As you can see, `react-select` let's you override a bunch of components with whatever you like. [Here are the related docs](https://deploy-preview-2289--react-select.netlify.com/components#replaceable-components).

_________________

So, what do we provide in cozy-ui?

Our use cases are quite varied. We'll want to overrride the `Option` component almost every time, the `Control` almost every time too, the `Menu` to add the forms, the `Group` or `GroupHeading` for bank, and probably more.

We could start by only shipping the most common replacement Components, for example the `Control` and a basic `Option`. The user would do something like this (slight oversimplification):

```
import Select from 'react-select';
import { Option, ControlButtton } from 'cozy-ui/react/select';

const MyAppSelect = () => (
  <Select
    components={{
      Option: Option,
      Control: ControlButtton
    }}
    />
);
```

This is cool but it creates a peer dependency. 

We could also ship `react-select` through `cozy-ui`. Since `react-select` is very customizable, we would need to re-export absolutely everything, on top of our own components. 
This might allow us to automatically inject our custom components, and it should make developing them easier. On the other hand, it means app will be constrained to the version of `react-select` shipped with cozy-ui.

If that sounds good to you, I can work on a POC PR. 

(summoning @edas )

**Comment by ptbrowne** [comment] 2018-03-16 14:48
> This is cool but it creates a peer dependency.

I think we could ask the application to install react-select.

> We could also ship react-select through cozy-ui. Since react-select is very customizable, we would need to re-export absolutely everything, on top of our own components.

I am not very fond of doing this, I think it is based on the premise that we should not be coupled to much to react-select and be able to change to a different lib if we want to. I have the impression that react-select is well built and that the premise could be "we have chosen react-select and we ship components that are compatible". I think it will be simpler to begin with, without being too risky.

**Comment by edas** [comment] 2018-03-16 15:07
Linking to the internal Trello where we talk with @y-lohse : https://trello.com/c/ZWXLfheS/875-3h-ui-composant-de-gestion-de-groupes-dun-contact#comment-5aaa9f98335715caee4c2ab7

1. Do not import react-select into cozy-ui, directly use in into each app
2. Import react-select in cozy-ui, then export everything as it, untouched
3. Import react-select in cozy-ui, add cozy style, then export the full functionalities
4. Import react-select in cozy-ui, add cozy style, then restrict to the minimum what we give access to, in order to maybe change the underlying component in the future
5. Define high level components dedicated to very precise purposes in cozy-ui (like "GroupSelector"), which may use react-select internally but completely hidden it from the final app

As I understand you, we need something like this in many apps. To be DRY and expose the choice already made, we probably at least go for 2 and not for 1. As we certainly need some style, it will probably be the 3rd solution anyways.

Solution 4 is probably my default choice for a situation like this but @y-lohse did convinced me that this component has too many usefull options and that we won't be able to switch to another internal component in the future without breaking something, so I exclude this solution.

The last one (5) is definitely the way to go everywhere we really use the same thing in two different apps. Question is: Is this the case ? If yes, go with solution 5, otherwise go with solution 3

**Comment by y-lohse** [comment] 2018-03-16 15:52
I don't think 5 will work right now — maybe once we have a better understanding of our various requirements. But right now, I'm quite convinced it's too early.

3 sounds good, but as mentioned, we don't *really* need to do that in order to get cozy styles. A simpler option might be to export only replacement components for react-select. A more complete example:

In cozy-ui:

```
export const SelectOption = ({ label, innerProps }) => (
  <div {...innerProps} className="cozy-option">
    {label}
  </div>
)
```

In the app:

```
import Select from "react-select";
import { SelectOption } from "cozy-ui/react";

export const MySelectComponent = () => (
  <Select 
    components={{
      Option: SelectOption
    }}
    />
)
```

… and like that, you receive a properly styled `Option` element, and `cozy-ui` doesn't have to bother with `react-select`. `cozy-ui` can export the most frequently used components like that.

The only advantage I see in importing and reexporting `react-select` is that we could automatically override some stuff in cozy-ui, for example:

```
import Select from "react-select";
import { SelectOption } from "./SelectOption";

export const CozySelect = (...props) => (
  <Select
    components={{ Option: SelectOption, ...props.components }}
    />
)
```

The risk is to somehow break the `react-select` API. i think we can always move towards this later. As @ptbrowne says, let's start simple.

**Comment by edas** [comment] 2018-03-16 15:56
I seen another advantage : not having everyone/app to know that the select is from elswhere, that it has to be added to the package.json as a new dependency, and for consistency not having components from multiple sources.
What's the cost ?

**Comment by y-lohse** [comment] 2018-03-16 16:10
> What's the cost ?

Probably just implementation time, making sure we don't accidentally break some `react-select` API. Nothing big though.

> that it has to be added to the package.json as a new dependency

Also, every app is locked on the same version of `react-select`. This means apps can't just update their own version to benefit from a bugfix, but we might also avoid some compatibility issues.

**Comment by y-lohse** [comment] 2018-03-23 10:05
I'm closing this issue since we have an extendable selectbox component now. Feel free to re-open it if you feel the root of the issue is not adressed!

**Closed by y-lohse** 2018-03-23 10:05 UTC
Labels: ⚙️ enhancement
